apiVersion: v1
kind: Service
metadata:
  name: eam-api-service
  namespace: eam-system
  labels:
    app: eam-api
    component: api
    tier: backend
    version: "5.0.0"
    app.kubernetes.io/name: eam-api
    app.kubernetes.io/version: "5.0.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: employee-activity-monitor
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app: eam-api
    component: api
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: eam-api-headless
  namespace: eam-system
  labels:
    app: eam-api
    component: api
    tier: backend
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: eam-api
    component: api
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Endpoints
metadata:
  name: eam-api-service
  namespace: eam-system
  labels:
    app: eam-api
    component: api
subsets: []
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eam-api-pdb
  namespace: eam-system
  labels:
    app: eam-api
    component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: eam-api
      component: api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eam-api-hpa
  namespace: eam-system
  labels:
    app: eam-api
    component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eam-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max