apiVersion: v1
kind: Service
metadata:
  name: eam-frontend-service
  namespace: eam-system
  labels:
    app: eam-frontend
    component: frontend
    tier: frontend
    version: "5.0.0"
    app.kubernetes.io/name: eam-frontend
    app.kubernetes.io/version: "5.0.0"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: employee-activity-monitor
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/nginx_status"
    prometheus.io/port: "80"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
  selector:
    app: eam-frontend
    component: frontend
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: eam-frontend-headless
  namespace: eam-system
  labels:
    app: eam-frontend
    component: frontend
    tier: frontend
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: eam-frontend
    component: frontend
  publishNotReadyAddresses: true
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eam-frontend-pdb
  namespace: eam-system
  labels:
    app: eam-frontend
    component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: eam-frontend
      component: frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eam-frontend-hpa
  namespace: eam-system
  labels:
    app: eam-frontend
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eam-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: nginx_requests_per_second
        target:
          type: AverageValue
          averageValue: "200"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max