apiVersion: v1
kind: Namespace
metadata:
  name: eam-system
  labels:
    name: eam-system
    app.kubernetes.io/name: eam
    app.kubernetes.io/version: "5.0.0"
    app.kubernetes.io/component: system
    app.kubernetes.io/part-of: employee-activity-monitor
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "Employee Activity Monitor v5.0 - Production Namespace"
    contact: "devops@company.com"
    cost-center: "IT-Operations"
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: eam-resource-quota
  namespace: eam-system
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "30"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: eam-limit-range
  namespace: eam-system
spec:
  limits:
    - default:
        cpu: "1000m"
        memory: "1Gi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
    - max:
        cpu: "4000m"
        memory: "8Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
      type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eam-network-policy
  namespace: eam-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: eam-system
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              name: monitoring
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: eam-system
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80