apiVersion: v2
name: eam
description: Employee Activity Monitor (EAM) v5.0 - Helm Chart
type: application
version: 5.0.0
appVersion: "5.0.0"
home: https://github.com/company/eam
sources:
  - https://github.com/company/eam
maintainers:
  - name: DevOps Team
    email: devops@company.com
keywords:
  - employee-monitoring
  - activity-tracker
  - dotnet
  - angular
  - postgresql
annotations:
  category: Monitoring
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled